In [1]:
import pandas as pd
import numpy as np

from sklearn import preprocessing

from sklearn.model_selection import train_test_split

In [2]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [31]:
from sklearn.metrics import classification_report , confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv("A:/MinorProjectData/GlobalTerrorCleanPartTwo.csv")

In [4]:
# Calculate the number of attacks by group
groups = data['gname'].value_counts()

# Include groups with at least 10 attacks
groups = groups[groups > 19]

# Exclude unknown groups
group_list = groups.index[groups.index != 'Unknown']

# Subset the data to major groups
major_groups = data[data['gname'].isin(group_list)]

# Display the number of attacks by group
major_groups['gname'].value_counts()

Taliban                                                  6558
Shining Path (SL)                                        4302
Islamic State of Iraq and the Levant (ISIL)              4261
Farabundo Marti National Liberation Front (FMLN)         2952
Al-Shabaab                                               2669
Irish Republican Army (IRA)                              2660
Revolutionary Armed Forces of Colombia (FARC)            2326
New People's Army (NPA)                                  2144
Boko Haram                                               2067
Kurdistan Workers' Party (PKK)                           2028
Basque Fatherland and Freedom (ETA)                      1993
Communist Party of India - Maoist (CPI-Maoist)           1766
Liberation Tigers of Tamil Eelam (LTTE)                  1554
Maoists                                                  1420
National Liberation Army of Colombia (ELN)               1381
Tehrik-i-Taliban Pakistan (TTP)                          1250
Palestin

In [49]:
seed = 42

#Predictor variables with one hot encoding for machine learning model to understand.

X = major_groups[['country', 'region', 'attacktype1', 'nkill','latitude','longitude','year']]

Y = major_groups['gname']

#Create an 80/30 split for training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = seed)

In [50]:
#Model Object
knn_model = KNeighborsClassifier(n_neighbors=5)

#Fitting the model
knn_model.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [51]:
knn_predictions = knn_model.predict(X_test)

In [52]:
knn_accuracy = accuracy_score(Y_test,knn_predictions)

print(knn_accuracy)

0.7922526420903719


In [53]:
print(classification_report(Y_test,knn_predictions))

                                                              precision    recall  f1-score   support

                                                      09-Feb       0.67      0.80      0.73         5
       16 January Organization for the Liberation of Tripoli       1.00      1.00      1.00         7
                          23rd of September Communist League       0.92      0.85      0.88        13
                                     Abdullah Azzam Brigades       0.00      0.00      0.00         5
                                Abu Nidal Organization (ANO)       0.17      0.30      0.21        10
                                      Abu Sayyaf Group (ASG)       0.85      0.93      0.89       132
                                              Action Directe       0.45      0.64      0.53        14
                    Adan-Abyan Province of the Islamic State       0.33      0.31      0.32        16
                    African National Congress (South Africa)       0.92      0.97

c:\users\siddharth kumar\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [42]:
print(confusion_matrix(Y_test,knn_predictions))

[[ 4  0  0 ...  0  0  0]
 [ 0  7  0 ...  0  0  0]
 [ 0  0 11 ...  0  0  0]
 ...
 [ 0  0  0 ...  3  0  0]
 [ 0  0  0 ...  0  7  0]
 [ 0  0  0 ...  0  0  2]]


In [43]:
print(accuracy_score(Y_test,knn_predictions))

0.7922526420903719
