# Weapon Type Classification 

# Decision Trees and Random Forest

Importing the needed libraries

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import time

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report , confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier

Importing The Dataset

In [7]:
data = pd.read_csv("A:/MinorProjectData/GlobalTerrorCleanPartTwo.csv")

In [8]:
data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'eventid', 'year', 'month', 'day',
       'extended', 'country', 'country_txt', 'region', 'region_txt',
       'provstate', 'city', 'latitude', 'longitude', 'specificity', 'vicinity',
       'crit1', 'crit2', 'crit3', 'doubtterr', 'multiple', 'success',
       'suicide', 'attacktype1', 'attacktype1_txt', 'targtype1',
       'targtype1_txt', 'targsubtype1', 'targsubtype1_txt', 'corp1', 'target1',
       'natlty1', 'natlty1_txt', 'gname', 'guncertain1', 'individual',
       'weaptype1', 'weaptype1_txt', 'weapsubtype1', 'weapsubtype1_txt',
       'nkill', 'nwound', 'property', 'ishostkid', 'dbsource', 'INT_LOG',
       'INT_IDEO', 'INT_MISC', 'INT_ANY'],
      dtype='object')

In [9]:
data.drop(labels = ['Unnamed: 0' , 'Unnamed: 0.1'] , axis=1 , inplace=True)

In [11]:
data.head()

eventid  year  month  day  extended  country         country_txt  \
0  197000000001  1970      7    2         0       58  Dominican Republic   
1  197000000002  1970      0    0         0      130              Mexico   
2  197001000001  1970      1    0         0      160         Philippines   
3  197001000002  1970      1    0         0       78              Greece   
4  197001000003  1970      1    0         0      101               Japan   

   region                   region_txt provstate   ...     \
0       2  Central America & Caribbean   Unknown   ...      
1       1                North America   Unknown   ...      
2       5               Southeast Asia    Tarlac   ...      
3       8               Western Europe    Attica   ...      
4       4                    East Asia   Unknown   ...      

         weapsubtype1_txt  nkill  nwound  property  ishostkid  dbsource  \
0                 Unknown    1.0     0.0         0        0.0      PGIS   
1                 Unknown    0.0     0.0         0        1.0      PGIS   
2                 Unknown    1.0     0.0         0        0.0      PGIS   
3  Unknown Explosive Type    0.0     0.0         1        0.0      PGIS   
4                 Unknown    0.0     0.0         1        0.0      PGIS   

   INT_LOG  INT_IDEO  INT_MISC  INT_ANY  
0        0         0         0        0  
1        0         1         1        1  
2       -9        -9         1        1  
3       -9        -9         1        1  
4       -9        -9         1        1  

[5 rows x 48 columns]

# Using Decision Trees

In [13]:
#Our Decision Tree model object
model = DecisionTreeClassifier()

In [34]:
#Training and Testing Data

#Predictor Variables
X = data[['country','targtype1','attacktype1','nkill','nwound']]

#Target Variable
Y = data['weaptype1_txt']

In [35]:
#Splitting the data into training and testing sets

X_train,X_test,Y_train,Y_test = train_test_split(X , Y , test_size = 0.3)

In [36]:
#Fitting the model using the training data
model.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [37]:
#Predicting the target variable using the decision tree model

predictions = model.predict(X_test)

In [38]:
#Classification Report 


print(classification_report(Y_test,predictions))

                           precision    recall  f1-score   support

               Biological       0.33      0.27      0.30        11
                 Chemical       0.36      0.33      0.34        86
Explosives/Bombs/Dynamite       0.95      0.96      0.96     25611
             Fake Weapons       0.11      0.09      0.10        11
                 Firearms       0.83      0.87      0.85     16064
               Incendiary       0.82      0.82      0.82      3059
                    Melee       0.41      0.25      0.31       978
                    Other       0.29      0.13      0.18        30
             Radiological       0.75      1.00      0.86         3
       Sabotage Equipment       0.17      0.06      0.09        33
                  Unknown       0.76      0.68      0.72      3805
 Vehicle (non-explosives)       0.27      0.27      0.27        33

              avg / total       0.88      0.88      0.88     49724



In [39]:
#Confusion Matrix 


print(confusion_matrix(Y_test,predictions))

[[    3     4     0     0     0     1     1     1     1     0     0     0]
 [    2    28    19     0     3     7    25     0     0     0     0     2]
 [    0    16 24593     2   890    26    25     0     0     0    57     2]
 [    1     0     1     1     3     3     0     0     0     0     2     0]
 [    0     6   868     2 13937   343   236     2     0     4   661     5]
 [    0     3    89     0   371  2514    29     1     0     4    48     0]
 [    2    18    33     2   573    43   244     4     0     0    48    11]
 [    1     2     2     0     8     3     5     4     0     0     2     3]
 [    0     0     0     0     0     0     0     0     3     0     0     0]
 [    0     0     1     0     6    23     0     1     0     2     0     0]
 [    0     0   170     2   908    96    27     1     0     2  2598     1]
 [    0     1     1     0     6     5    10     0     0     0     1     9]]


In [40]:
#Accuracy Measure
accuracy_score(Y_test, predictions)

0.8835974579679833

# Using Random Forest Classification

In [41]:
#Our model object
rfc = RandomForestClassifier()

In [42]:
#Fitting / Training the model using the training set
rfc.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [43]:
#Predicting The Target Variable

rfcpredictions = rfc.predict(X_test)

In [44]:
#Classification Report

print(classification_report(Y_test,predictions))

                           precision    recall  f1-score   support

               Biological       0.33      0.27      0.30        11
                 Chemical       0.36      0.33      0.34        86
Explosives/Bombs/Dynamite       0.95      0.96      0.96     25611
             Fake Weapons       0.11      0.09      0.10        11
                 Firearms       0.83      0.87      0.85     16064
               Incendiary       0.82      0.82      0.82      3059
                    Melee       0.41      0.25      0.31       978
                    Other       0.29      0.13      0.18        30
             Radiological       0.75      1.00      0.86         3
       Sabotage Equipment       0.17      0.06      0.09        33
                  Unknown       0.76      0.68      0.72      3805
 Vehicle (non-explosives)       0.27      0.27      0.27        33

              avg / total       0.88      0.88      0.88     49724



In [45]:
#Confusion Matrix 

print(confusion_matrix(Y_test,predictions))

[[    3     4     0     0     0     1     1     1     1     0     0     0]
 [    2    28    19     0     3     7    25     0     0     0     0     2]
 [    0    16 24593     2   890    26    25     0     0     0    57     2]
 [    1     0     1     1     3     3     0     0     0     0     2     0]
 [    0     6   868     2 13937   343   236     2     0     4   661     5]
 [    0     3    89     0   371  2514    29     1     0     4    48     0]
 [    2    18    33     2   573    43   244     4     0     0    48    11]
 [    1     2     2     0     8     3     5     4     0     0     2     3]
 [    0     0     0     0     0     0     0     0     3     0     0     0]
 [    0     0     1     0     6    23     0     1     0     2     0     0]
 [    0     0   170     2   908    96    27     1     0     2  2598     1]
 [    0     1     1     0     6     5    10     0     0     0     1     9]]


In [46]:
#Accuracy Of  Random Forest Model

accuracy_score(Y_test,rfcpredictions)

0.8911591987772505